"use client";
import { MainLayout } from "@/layout/MainLayout";
import "./globals.css";
import type { Metadata } from "next";
import { Calligraffitti, Montserrat } from "next/font/google";
import { useCallback, useEffect, useState } from "react";
import { getUser } from "./signin/utils/function";
import { useUserContext } from "@/hooks/useUser";
import { User } from "../../typings";
import { UserProvider } from "@/context/UserContext";
import { CartProvider } from "@/context/CartContext";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <UserProvider>
          <CartProvider>
            <MainLayout>{children}</MainLayout>
          </CartProvider>
        </UserProvider>
      </body>
    </html>
  );
}
